[project]
name = "hw0203"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.11.14"
dependencies = [
    "langchain-core==1.2.8",
    "langchain-openai>=1.1.7",
]
